spring:
#  application:
#    name: common
#  datasource:
#    url: jdbc:mysql://localhost:3306/demo
#    type: com.alibaba.druid.pool.DruidDataSource
#    password: VcaHmg0!qBeayg$ku6f~_Q1vtalQ4egu
#    username: root
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl